# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: bomLog
email: bomlee427@gmail.com
locale: ko
url: "http://bomlee427.github.io"
repository: "Bomlee427/bomlee427.github.io"
description: >- # this means to ignore newlines until "baseurl:"
  무슨 생각을 해...그냥 하는 거지
twitter_username:
github_username: BomLee427
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
# remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Seoul # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
date_format: "%Y/%m/%d"

# Markdown settings
kramdown:
  # auto_ids: false
  # enable_coderay: false
  # entity_output: as_char
  # footnote_nr: 1
  # smart_quotes: lsquo,rsquo,ldquo,rdquo
  # toc_levels: 1..6
  hard_wrap: true

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-target-blank
  - jekyll-last-modified-at

author:
  name   : "Bom"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "무슨 생각을 해...그냥 하는 거지"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bomlee427"

# footer:
#   links:
#     - label: "Twitter"
#       icon: "fab fa-fw fa-twitter-square"
#       url: "https://twitter.com/"
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/"
#     - label: "Instagram"
#       icon: "fab fa-fw fa-instagram"
#       url: "https://instagram.com/"

# last-modified-at:
# ​    date-format: "%Y/%M/%D"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# Analytics
analytics:
  provider : "google-gtag"  # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id : "G-4N0XD0K9W3"
    anonymize_ip : # true, false (default)
